# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: MainPSScriptAnalyzer

on:
  push:
    branches: ["main"]
    paths:
      - "**.ps1"
      - "**.psm1"
      - "**.psd1"
  pull_request:
    branches: ["main"]
    paths:
      - "**.ps1"
      - "**.psm1"
      - "**.psd1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyzer:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
        with:
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\
          recurse: true
          # Include your own basic security rules. Removing this option will run all the rules
          includeRule: '"AlignAssignmentStatement","AvoidAssignmentToAutomaticVariable","AvoidDefaultValueForMandatoryParameter","AvoidDefaultValueSwitchParameter","AvoidGlobalAliases","AvoidGlobalFunctions","AvoidGlobalVars","AvoidInvokingEmptyMembers","AvoidMultipleTypeAttributes","AvoidNullOrEmptyHelpMessageAttribute","AvoidOverwritingBuiltInCmdlets","AvoidSemicolonsAsLineTerminators","AvoidShouldContinueWithoutForce","AvoidTrailingWhitespace","AvoidUsingBrokenHashAlgorithms","AvoidUsingCmdletAliases","AvoidUsingComputerNameHardcoded","AvoidUsingConvertToSecureStringWithPlainText","AvoidUsingDeprecatedManifestFields","AvoidUsingDoubleQuotesForConstantString","AvoidUsingEmptyCatchBlock","AvoidUsingInvokeExpression","AvoidUsingPlainTextForPassword","AvoidUsingPositionalParameters","AvoidUsingUsernameAndPasswordParams","AvoidUsingWMICmdlet","AvoidUsingWriteHost","DSCDscExamplesPresent","DSCDscTestsPresent","DSCReturnCorrectTypesForDSCFunctions","DSCStandardDSCFunctionsInResource","DSCUseIdenticalMandatoryParametersForDSC","DSCUseIdenticalParametersForDSC","DSCUseVerboseMessageInDSCResource","MisleadingBacktick","MissingModuleManifestField","PlaceCloseBrace","PlaceOpenBrace","PossibleIncorrectComparisonWithNull","PossibleIncorrectUsageOfAssignmentOperator","PossibleIncorrectUsageOfRedirectionOperator","ProvideCommentHelp","ReservedCmdletChar","ReservedParams","ReviewUnusedParameter","ShouldProcess","UseApprovedVerbs","UseBOMForUnicodeEncodedFile","UseCmdletCorrectly","UseCompatibleCmdlets","UseCompatibleCommands","UseCompatibleSyntax","UseCompatibleTypes","UseConsistentIndentation","UseConsistentWhitespace","UseCorrectCasing","UseDeclaredVarsMoreThanAssignments","UseLiteralInitializerForHashtable","UseOutputTypeCorrectly","UseProcessBlockForPipelineCommand","UsePSCredentialType","UseShouldProcessForStateChangingFunctions","UseSingularNouns","UseSupportsShouldProcess","UseToExportFieldsInManifest","UseUsingScopeModifierInNewRunspaces","UseUTF8EncodingForHelpFile","PSAvoidUsingCmdletAliases"'
          output: results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
