name: PublishOnRelease

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Write-host $PSVersionTable.PSVersion.ToString()
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -confirm:$false -Force
          .\tasks.ps1 'build'
          $version = (Import-PowerShellDataFile -Path "$PSScriptRoot\PSTemplator\PSTemplator.psd1").ModuleVersion.ToString()
          $targetDir = "output\PSTemplator\$version"
          Publish-Module -Path $targetDir -NuGetApiKey $env:NUGET_KEY -Verbose
